@url_dev = http://localhost:3055/v1/api

#### Sign Up
POST {{url_dev}}/shop/signup HTTP/1.1
Content-Type: application/json
x-api-key: f66e6be7e1c642efdd3188ccefa453330ad67ead6fbf883a7e9c6da0e95383a460cb3153b314691947f0da53a5241d147897859808385131d09a2e81b4bb7254

{
    "name": "Shop NDTien",
    "email": "ndtien12test@gmail.com",
    "password": "abc1234"
}

### Login
POST {{url_dev}}/shop/login HTTP/1.1
Content-Type: application/json
x-api-key: f66e6be7e1c642efdd3188ccefa453330ad67ead6fbf883a7e9c6da0e95383a460cb3153b314691947f0da53a5241d147897859808385131d09a2e81b4bb7254

{
    "email": "ndtien12222143@gmail.com",
    "password": "abc1234"
}

### logout
POST {{url_dev}}/shop/logout HTTP/1.1
Content-Type: application/json
x-api-key: f66e6be7e1c642efdd3188ccefa453330ad67ead6fbf883a7e9c6da0e95383a460cb3153b314691947f0da53a5241d147897859808385131d09a2e81b4bb7254
x-client-id:66281a4b3fd6b809d678c9f1
authorization:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjI4MWE0YjNmZDZiODA5ZDY3OGM5ZjEiLCJlbWFpbCI6Im5kdGllbjEydGVzdEBnbWFpbC5jb20iLCJpYXQiOjE3MTM5MDQyMDUsImV4cCI6MTcxNDA3NzAwNX0.W5U41lZ9yNsCce7hqMPcX1ezB670dfh0SPsYmKPsrj_rL7gyB4EHw9ilPkuBuWt67g9zAaJN7_kgoGxFM-4crgxzGupL1EYSsjHRMOLGsk0rYXI3jyYjIzBaOrEZdXpzCjMxNKWARJFg2mojya_f03Fz4Z5fuybg7r4UdXgMPDZSFvHNug6_7Q08OcL4r78YJiA6XOl8Cmj39fheTlQtxCpeXGp9EfuT69--8sOs0PufF4-8KQ4WAYCAhwEOGfT29XwlfpnM2rFVwJ9jVpQX5Dgsi3fq8Gw7kTYPjCRe-U3v_9vtBOzV_0d6c48bZImNzZbKJYDjOxaHJV0xNdTFlRS6ZKZJNRq3riMYP1IeTn80n4CySP3xeU4a455kYnO5jQSIOUERvTYdAuJDSpjch9bodaCQu-mp-GagUV4Wk2NOl4ZXEi1kpzUmFgLIQgMGPWAY_AqigH7EJxniwcq2HLPCMqmB5GVCik_LdJPUcCSdRsjikTxmf6E6Ggsop6RscA0zEE5PiHBca2Dg7-UMtcTRE89sKMJe0CX79GJHpafeIKYFlZnMlTbdnPtYD6UbduI9G_ChzjK-Gf8XXXZfAKo2X0adCeSiobgBw3dbznlCBmhYi2z1WwpT9o_kGdUqkEZ5Z2lTUbUFTu79aNMwLRUkeYtwN-6V2-g91wDhcd0